warehouse/lib/warehouse_web/router.ex
defmodule WarehouseWeb.Router do
  use WarehouseWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :guardian do
    plug WarehouseWeb.Authentication.Pipeline
  end

  pipeline :browser_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WarehouseWeb do
    pipe_through [:browser, :guardian]

    get "/", PageController, :index
    resources "/clothes", ClotheInStoreController
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
    resources "/checks", SalesRecepeitController, only: [:index, :show]
  end

  scope "/api", WarehouseWeb.Api, as: :api do
    pipe_through :api
    get "/orders/:id/:clothe/:employee", ClotheOrderController, :order
  end

  scope "/admin", WarehouseWeb.Sales do
    pipe_through [:browser, :guardian, :browser_auth]
    resources "/magazines", MagazineController, only: [:index]
    resources "/employee", EmployeeController, only: [:index]
  end

  scope "/admin", WarehouseWeb do
    pipe_through [:browser, :guardian, :browser_auth]
    resources "/orders", ClotheOrderController
  end

  # Other scopes may use custom stacks.
  # scope "/api", WarehouseWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: WarehouseWeb.Telemetry
    end
  end
end

warehouse/lib/warehouse_web/views/layout_view.ex
defmodule WarehouseWeb.LayoutView do
  use WarehouseWeb, :view
  import WarehouseWeb.Authentication
end

warehouse/lib/warehouse_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
      <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <ul class="navbar-nav mr-auto">
                  <%= link("Покупка одежды", to: Routes.clothe_in_store_path(@conn, :index), class: "navbar-brand navbar-text text-dark h1") %>
                  <%= link("Чеки", to: Routes.sales_recepeit_path(@conn, :index), class: "navbar-brand navbar-text text-dark h1") %>
                  <%= if logged?(@conn) do %>
                    <%= link("Магазины", to: Routes.magazine_path(@conn, :index), class: "navbar-brand navbar-text text-dark h1") %>
                    <%= link("Сотрудники", to: Routes.employee_path(@conn, :index), class: "navbar-brand navbar-text text-dark h1") %>
                    <%= link("Заказы одежды", to: Routes.clothe_order_path(@conn, :index), class: "navbar-brand navbar-text text-dark h1") %>
                  <% end %>
                </ul>
                <span class="navbar-text">
                    <%= if logged?(@conn) do %>
                    <h2 class="text-dark">
                      Добро пожаловать, <%= current_user(@conn).first_name %>!
                    </h2>
                    <h2>
                      <%= link(
                        "Выйти",
                        to: Routes.session_path(@conn, :delete),
                        method: :delete)
                      %>
                    </h2>
                  <% else %>
                    <h2>
                      <%= link("Войти", to: Routes.session_path(@conn, :create)) %>
                    </h2>
                  <% end %>
                </span>
            </nav>
    </header>

    <div class="container">
    <%= if get_flash(@conn, :success) do %>
      <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>
    <% end %>
    <%= if get_flash(@conn, :info) do %>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <% end %>
    <%= if get_flash(@conn, :error) do %>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <% end %>
      <%= @inner_content %>
    </div>
  </body>
</html>